In [3]:
import numpy as np
import pandas as pd

<h3>Check numpy version</h3>

In [31]:
np.__version__

'1.26.4'

<h3>Create arrays from Python lists</h3>

In [33]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

<h3>Explicitly set the data type of the resulting array</h3>

In [35]:
arr= np.array([1,2,3,4,5], dtype= "float32")
arr

array([1., 2., 3., 4., 5.], dtype=float32)

<h3>Creating arrays from scratch</h3>

In [38]:
arr= np.zeros(10)# Array filled with zeros
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
arr= np.ones((3,3))# 3x3 array filled with 1s
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
arr= np.full((3,4), 3.14)# 3x4 array filled with3.14
arr

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [45]:
arr= np.arange(0, 20, 2)# Create an array starting from 0 to 20, stepping by 2 
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
arr= np.linspace(0, 21, 7)# Create an array with values from 0 to 21 with 7 evenly spaced integers
arr

array([ 0. ,  3.5,  7. , 10.5, 14. , 17.5, 21. ])

In [49]:
arr= np.random.random((2,2))# 2x2 array of random values uniformly distributed between 0 and 1
arr

array([[0.97874179, 0.50160821],
       [0.73920316, 0.57810201]])

In [51]:
arr= np.random.randint(0,20, (4,5))#4x5 array of random integers between 0 and 20
arr

array([[ 7, 10, 11, 18,  5],
       [ 7,  1, 11,  0,  4],
       [ 6, 15,  2, 13,  3],
       [11,  6, 10, 19, 13]])

In [53]:
arr= np.eye(3)# Create a 3x3 identity matrix
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
arr= np.empty(4)# Create an uninitialized array of four values
arr

array([0.97874179, 0.50160821, 0.73920316, 0.57810201])

<h3>NumPy array attributes</h3>

In [56]:
x= np.random.randint(10, size=(3,4,5))# 3d array
x

array([[[0, 3, 0, 5, 2],
        [3, 4, 3, 9, 4],
        [7, 3, 0, 8, 0],
        [5, 0, 7, 3, 5]],

       [[1, 1, 2, 3, 5],
        [6, 1, 8, 7, 8],
        [4, 9, 1, 4, 6],
        [5, 9, 7, 4, 7]],

       [[2, 1, 2, 5, 0],
        [8, 3, 1, 7, 1],
        [5, 1, 1, 2, 8],
        [6, 8, 0, 1, 3]]])

In [57]:
x.ndim #Check the number of dimensions

3

In [58]:
x.shape # Check the size of each dimension

(3, 4, 5)

In [59]:
x.size# Check the total size of the array

60